const mongoose = require("mongoose");
const dotenv = require("dotenv");
const User = require("./models/User");
const Transaction = require("./models/Transaction");
const AuditLog = require("./models/AuditLog");

// Load Environment variables
dotenv.config();

const MONGO_URI = process.env.MONGO_URI;

if (!MONGO_URI) {
  console.error("Error: MONGO_URI is not set in backend/.env file.");
  process.exit(1);
}

const statuses = ["Paid", "Failed", "Refunded", "Cancelled", "Created"];
const statusDistribution = [
  ...Array(80).fill("Paid"),
  ...Array(10).fill("Failed"),
  ...Array(5).fill("Refunded"),
  ...Array(3).fill("Cancelled"),
  ...Array(2).fill("Created"),
];

const paymentMethods = ["UPI", "Card", "NetBanking", "COD"];
const paymentDistribution = [
  ...Array(40).fill("UPI"),
  ...Array(30).fill("Card"),
  ...Array(20).fill("NetBanking"),
  ...Array(10).fill("COD"),
];

function getRandomItem(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

async function seed() {
  try {
    console.log("Connecting to MongoDB...");
    await mongoose.connect(MONGO_URI);
    console.log("Connected successfully.");

    // 1. Get or Create a User to associate transactions
    let user = await User.findOne();
    if (!user) {
      console.log("No user found. Creating a test user...");
      user = new User({
        fullName: "Karan Myntra Test",
        email: "test@myntraclone.com",
        password: "hashedpassword123", // Dummy password
      });
      await user.save();
      console.log(`Created test user: ${user.email} (ID: ${user._id})`);
    } else {
      console.log(`Using existing user: ${user.fullName} (${user.email})`);
    }

    // 2. Clear old transactions and audit logs
    console.log("Cleaning existing transactions and audit logs for this user...");
    const oldTransactions = await Transaction.find({ userId: user._id });
    const oldTxnIds = oldTransactions.map(t => t._id);
    
    await Transaction.deleteMany({ userId: user._id });
    await AuditLog.deleteMany({ transactionId: { $in: oldTxnIds } });
    console.log("Cleanup complete.");

    // 3. Generate 10,100 Transactions
    const TOTAL_RECORDS = 10100;
    console.log(`Generating ${TOTAL_RECORDS} transactions...`);

    const transactionsToInsert = [];
    const now = Date.now();

    for (let i = 0; i < TOTAL_RECORDS; i++) {
      const status = getRandomItem(statusDistribution);
      const paymentMethod = getRandomItem(paymentDistribution);
      
      let gateway = "None";
      if (paymentMethod === "UPI" || paymentMethod === "NetBanking") {
        gateway = "Razorpay";
      } else if (paymentMethod === "Card") {
        gateway = "Stripe";
      }

      const amount = Math.floor(199 + Math.random() * 14800); // 199 to 14999
      const randDays = Math.floor(Math.random() * 180); // within last 180 days
      const randMs = Math.floor(Math.random() * 24 * 60 * 60 * 1000);
      const dateTime = new Date(now - (randDays * 24 * 60 * 60 * 1000) - randMs);

      // Unique identifiers
      const transactionId = `TXN-${now - randDays * 100000 - i}-${Math.floor(1000 + Math.random() * 9000)}`;
      const invoiceId = `INV-${dateTime.getFullYear()}${(dateTime.getMonth() + 1).toString().padStart(2, '0')}${dateTime.getDate().toString().padStart(2, '0')}-${100000 + i}`;
      const gatewayTransactionId = gateway !== "None" ? `pay_${Math.random().toString(36).substring(2, 12)}` : null;
      
      let gatewayResponseCode = null;
      if (status === "Paid" || status === "Refunded") {
        gatewayResponseCode = "SUCCESS";
      } else if (status === "Failed") {
        gatewayResponseCode = getRandomItem(["BAD_CREDENTIALS", "INSUFFICIENT_FUNDS", "GATEWAY_TIMEOUT"]);
      } else if (status === "Cancelled") {
        gatewayResponseCode = "USER_ABORTED";
      }

      transactionsToInsert.push({
        userId: user._id,
        transactionId,
        invoiceId,
        amount,
        currency: "INR",
        gateway,
        gatewayTransactionId,
        gatewayResponseCode,
        paymentMethod,
        status,
        dateTime,
        webhookIdempotencyKey: status !== "Created" ? `evt_${Math.random().toString(36).substring(2, 12)}` : null,
        metadata: {
          notes: "Generated by testing database seed script",
          ip: "192.168.1.10",
        }
      });
    }

    // Insert Transactions in chunks to optimize memory and speed
    const CHUNK_SIZE = 2000;
    let insertedTransactions = [];
    
    for (let i = 0; i < transactionsToInsert.length; i += CHUNK_SIZE) {
      const chunk = transactionsToInsert.slice(i, i + CHUNK_SIZE);
      const docs = await Transaction.insertMany(chunk);
      insertedTransactions = insertedTransactions.concat(docs);
      console.log(`Inserted transactions: ${insertedTransactions.length}/${TOTAL_RECORDS}`);
    }

    // 4. Generate & Insert Audit Logs in Bulk
    console.log("Generating audit logs for inserted transactions...");
    const auditLogsToInsert = [];

    for (const txn of insertedTransactions) {
      // Every transaction starts as 'Created'
      auditLogsToInsert.push({
        transactionId: txn._id,
        eventType: "Created",
        timestamp: new Date(txn.dateTime.getTime() - 2000), // 2 seconds before
        actor: "User: " + user._id,
        metadata: { client: "App Client", action: "initiated" }
      });

      // If its status transitioned, log that transition
      if (txn.status !== "Created") {
        let actor = "System: Webhook";
        if (txn.status === "Cancelled") {
          actor = "User: " + user._id;
        }

        auditLogsToInsert.push({
          transactionId: txn._id,
          eventType: txn.status,
          timestamp: txn.dateTime,
          actor: actor,
          metadata: {
            gateway: txn.gateway,
            gatewayTxnId: txn.gatewayTransactionId,
            responseCode: txn.gatewayResponseCode,
            eventId: txn.webhookIdempotencyKey
          }
        });
      }
    }

    console.log(`Inserting ${auditLogsToInsert.length} audit logs in chunks...`);
    for (let i = 0; i < auditLogsToInsert.length; i += CHUNK_SIZE) {
      const chunk = auditLogsToInsert.slice(i, i + CHUNK_SIZE);
      await AuditLog.insertMany(chunk);
      console.log(`Inserted audit logs: ${Math.min(i + CHUNK_SIZE, auditLogsToInsert.length)}/${auditLogsToInsert.length}`);
    }

    console.log("\nSeeding finished successfully!");
    console.log(`Total transactions created: ${TOTAL_RECORDS}`);
    console.log(`Total audit logs created: ${auditLogsToInsert.length}`);
    console.log(`Test user ID: ${user._id}`);
    console.log(`Test user Email: ${user.email}`);

    mongoose.connection.close();
  } catch (error) {
    console.error("Seeding failed:", error);
    mongoose.connection.close();
    process.exit(1);
  }
}

seed();
